/* eslint-disable */
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_UPDATE_QUANTITIES = 'CART_UPDATE_QUANTITIES';

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const ADD_PRODUCT_TO_CART_ERROR = "ADD_PRODUCT_TO_CART_ERROR";

export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const GET_CART_ITEMS_WITHOUT_LOGIN = "GET_CART_ITEMS_WITHOUT_LOGIN";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const RESET_CART_AFTER_LOGOUT = "RESET_CART_AFTER_LOGOUT";

export const GET_COUNT = "GET_COUNT";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";

export const PLACE_ORDER = "PLACE_ORDER";

export const REVIEW_ORDER = "REVIEW_ORDER";